### PR TITLE
License owner

### PR DESCRIPTION
**Pull request by vgarvardt**

### CODE REVIEW

**Comment by s4nji** [comment]
+1

Approved with Zappr  Approved with Zappr

**Comment by RTodorov** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by tammymendt** [comment]
Hey, I've stopped working at HelloFresh for over two years now and am
getting these emails.

**Comment by vgarvardt** [comment]
@tammymendt un-watch the repo and you'll stop recieveng these emails. This is public repo with OSS project.

**Pull request merged**
